### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by SingularisArt** [nanotee/sqls.nvim#17]
Hello all.

I was wondering how do I setup everything up?
I don't know what to do or where to go to get the needed information to set up the lsp.

Could you direct me on where to go, what to do, etc?

Thanks

**Comment by SingularisArt** [comment]
When I put:

```lua
require('lspconfig').sqls.setup{
    on_attach = function(client, bufnr)
        require('sqls').on_attach(client, bufnr)
    end
}
```

in my init.lua, I get the following error: LSP[sqls] no database connection

**Comment by nanotee** [comment]
`sqls` expects users to configure at least one database connection, there are examples in the `sqls` README: https://github.com/lighttiger2505/sqls#db-configuration

**Comment by SingularisArt** [comment]
Here's my configuration file:

```yaml
# Set to true to use lowercase keywords instead of uppercase.
lowercaseKeywords: true
connections:
  - alias: my_alias
    driver: mysql
    proto: tcp
    user: USER_NAME
    passwd: PASSWORD
    host: 127.0.0.1
    port: 3306
    dbName: mysql
    params:
      autocommit: "true"
      tls: skip-verify
```

but I keep getting the following error: `LSP[sqls][Info] cannot ping to database, dial tcp 127.0.0.1:3306: connect: connection refused`.

Am I missing a step?
